; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = interrupciones_heltec_lora32

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:interrupciones_heltec_lora32]
board = heltec_wifi_lora_32_V3
build_src_filter = -<*> +<interrupciones.cpp>
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.12.1
    adafruit/Adafruit SSD1306 @ ^2.5.15

[env:timers_heltec_lora32]
board = heltec_wifi_lora_32_V3
build_src_filter = -<*> +<timers.cpp>

[env:conversionAD_esp32dev]
board = esp32dev
build_src_filter = -<*> +<conversionAD.cpp>

[env:pwm_esp32dev]
board = esp32dev
build_src_filter = -<*> +<pwm.cpp>
lib_deps = madhephaestus/ESP32Servo @ ^0.13.0
